### ISSUE TITLE
[BUG] Bug in windows store WSL Manager version number

### ISSUE THREAD

**Issue by Felipe-Linhares** [bostrot/wsl2-distro-manager#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

bug in windows store wsl manager version number

### Expected Behavior

bug in windows store wsl manager version number

### Steps To Reproduce

1. bug in windows store wsl manager version number

### Environment

```markdown
- Windows Version: bug in windows store wsl manager version number
- WSL Distro Manager Version: 1.6.1
- WSL Version: 1.1.3.0
- Source: Windows Store
```

### Anything else?

I managed to solve the bug, I don't know if it was the right way, but I did it, I hope I helped in some way.

- constants.dart
![image](https://user-images.githubusercontent.com/70000056/227052182-2542bb63-55ba-4186-8c7c-5fb8a7f7bd79.png)

- main.dart
![image](https://user-images.githubusercontent.com/70000056/227052330-9128b21a-f302-4c38-a346-1a5c2c693403.png)

- result
![image](https://user-images.githubusercontent.com/70000056/227052787-0606a7ed-6afd-48dc-a617-8f065043ff3c.png)

**Comment by bostrot** [comment]
Thanks for reporting.

I created the msix manually before submitting it to the store and forgot to update the version number. With PR #115 the GitHub Action workflow will automatically update it in the constants.dart file and build it so that won't happen again.

Reading the pubspec.yaml from a release probably doesn't work as expected as it is not in the built folder unless copied manually. 

Not sure if it is changed by now but the only way (at least at the time of writing that part) to get the version number was reading out the windows build files where the version also had to be entered manually. 

So I guess using the workflow is probably the best solution right now. (correct me if I am wrong)

**Comment by Felipe-Linhares** [comment]
ah, I understand, well I'm not sure, but if it worked that's what matters
