### ISSUE TITLE
Multilanguage Support

### ISSUE THREAD

**Issue by pauloinfoluck** [bostrot/wsl2-distro-manager#33]
I found the project very interesting.
CMD is good but the GUI is always welcome.

I wanted to know if you have the possibility to include a multilingual system for the basic options, it would be nice and I'm sure a lot of people would help with localization.

As the options are very simple.. The location would be quiet.

If you allow, I can do that, it would be very good for the tool.

**Comment by bostrot** [comment]
I actually thought about doing that but wasn't sure about the demand.
You are free to add a PR!

Otherwise I will add it to my todo list :)

**Comment by bostrot** [comment]
So I added the base for localizations with the PR #34. You can find a build in the [multilanguage branch build folder](https://github.com/bostrot/wsl2-distro-manager/tree/multilanguage/build/windows/runner/Release).

Right now I added english and german support (german with google translate: probably needs some checks).

Localizations are saved in `/lib/i18n/` as json files. New languages can be added either directly in the appropriate json file (e.g. `en.json`) or via the localizations [windows/mac application](https://github.com/Flutterando/localization/releases) which provides a GUI.

As of some restrictions with fluent_ui package currently it is easier not to use the country code in the file name so instead of `en_US.json` just `en.json`.
