### ISSUE TITLE
Directory/name mixed up for new distro

### ISSUE THREAD

**Issue by eekboom** [bostrot/wsl2-distro-manager#7]
I tried to create a second Ubuntu 20.04 version using the tool.
As name I chose Ubuntu-Home, and for "Save location" I clicked on the folder icon, navigated to "D:\" and created a new folder "wsl2".

After that my running ubuntu 20.04 instance was terminated without any warning (which is another bug, imho).

Then the tool's windows shows "Creating Ubuntu-Home. This might take a while..." and disturbingly shows "No distros found." (which hopefully also is another bug - or did it delete my existing distro?).
Because it really was taking quite a while and nothing at all happened in the newly created "D:\wsl2\" directory, I opened Process Explorer to check if it's doing anything at all.
I noticed a process another process that is doing an wsl export to "D:\wsl2Ubuntu-Home" - notice the missing "\".

Ok, finally I ended up with a working second distro, just with the wrong name in the wrong location.

Thankfully, my existing distro still works, so I guess the "No distros found" should be "Distro configuration in process" or something.

**Comment by bostrot** [comment]
Thanks for reporting. I have encountered the same and am currently working on this.

To clarify this behavior:

Right now creating a second instance with the same distro (without specifying a custom rootfs) works by copying the rootfs of an existing instance to a new location which is bad labeled and not optimal I guess. An option to make it better would currently only be to automate the rootfs download and use that as the fs to build the instance from.
Now the "tricky" part is that some rootfs (e.g. Kali or Debian) can only be downloaded in an appimage format (as far as I can tell). So that would first have to be renamed and extracted as per windows docs. 

The shutting down is performed by the WSL export command. While an instance is in an exporting or importing stage it is not shown as an available distro.

Note: specifying a location path is optional. I hope that is clear or do I need to clarify this better? 

I guess these would be the ToDos regarding this issue:

- [ ] Create a second distro with extra downloaded/extracted rootfs
- [ ] Change no distros found to something less permanent

I also thought about making a copy of the rootfs right after the first instance of a distro has been installed by windows to skip double downloading them but then the insta ces would have to be created by this app for that to work (which I think is bad).

**Comment by bostrot** [comment]
This should be fixed with release [v0.7.0](https://github.com/bostrot/wsl2-distro-manager/releases/tag/v0.7.0).
